site_name: MkDocs Test Docs Ivan
Site_description: Тестируем MkDocs самостоятельно через GitHub Pages
theme: material

nav:
  - Главная: index.md
  - О курсе: About.md
  - Справочник API: dist/index.html
  - Контакты: Контакты.md
  - Благодарность: Gratitude.md
  
